//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTaiKhoan
    {
        public int ID { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string SDT { get; set; }
        public bool GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public byte[] AnhDaiDien { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
