//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DongHo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DongHo()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public int MaThuongHieu { get; set; }
        public string MaSP { get; set; }
        public string XuatSu { get; set; }
        public string GioiTinhSP { get; set; }
        public string ChatLieuMatKinh { get; set; }
        public string BoMayNangLuong { get; set; }
        public string MauMatSo { get; set; }
        public string ChatLieuDay { get; set; }
        public double BeDayMatSo { get; set; }
        public double DuongKinhMatSo { get; set; }
        public string HinhDangMatSo { get; set; }
        public string MucChongNuoc { get; set; }
        public byte[] HinhAnh { get; set; }
        public double GiaTriBaoHanh { get; set; }
        public decimal GiaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> MaKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
